<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

In [4]:
import numpy as np

```EXERCISE 1```

| Term  |  Brief description  |
| :--- | --: | 
| Subsetting  |  Subsetting means 'selecting', the umbrella term for everything below |  
| Indexing   |  Refers to selecting the particular element corresponding to that index  |  
| Slicing   |  Refers to selecting a range of elements from the certain list  |   
| Masking   |  Subsetting in *NumPy ONLY*, testing a condition and selecting elements based off that condition |

```EXERCISE 2```

In [5]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [6]:
odd=np_array_2d[:,0]  #Getting the numbers out of the nested list
print(odd) 

['1' '3' '2' '4' '5' '7' '6' '8' '10' '9']


In [33]:
odd.astype(int) #turning them from str into integer type

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [34]:
odd.astype(int)%2 #Getting remainders (1 = odd no., 0 = even no.)

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [35]:
mask = odd.astype(int)%2==1 #Masking, True = odd no., False = even no.
mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [36]:
ans = np_array_2d[mask,1] #Extracting the letter (at index 1) from the specific elements that I got from my mask
print(ans)

['A' 'C' 'E' 'G' 'I']
