<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [1]:
import numpy as np

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [6]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]

x = py_list

In [8]:
#FIRST ELEMENT
x[0]

'a1'

In [9]:
#LAST ELEMENT
x[-1]

'j10'

In [13]:
#INDEX 0 to 3
x[0:3]
#You do not get 4 items, you get 3-0=3 elements: the number of elements

['a1', 'b2', 'c3']

In [15]:
x[1:3]
#expect 3-1=2 elements only that start at index '1'

['b2', 'c3']

In [17]:
x[1:6]
#Gives 6-1=5 elements starting at index 1

['b2', 'c3', 'd4', 'e5', 'f6']

In [19]:
#TAKING STEPS
x[1:6:2]
#Index 1 to 5 in steps of 2

['b2', 'd4', 'f6']

In [21]:
#INDEX 5 to the end
x[5:]

['f6', 'g7', 'h8', 'i9', 'j10']

In [23]:
x[5::2]

['f6', 'h8', 'j10']

In [25]:
#INDEX from the start to the 5-0=5 elements
x[:5]

['a1', 'b2', 'c3', 'd4', 'e5']

In [28]:
#iNDEX 5 to 3 in reverse
x[5:2:-1] #gives 5-2=3 elements, starting at the 5th element from the back

['f6', 'e5', 'd4']

In [30]:
#REVERSES the list
x[::-1]

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

## 1.2 Arrays only | Subsetting by masking

MASKING

In [31]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [33]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [34]:
np_array[np_array>3]#without needing to create a new variable

array([ 4,  5,  6,  7,  8,  9, 10])

In [42]:
#EXAMPLE 1 - using ~ to invert, asking for what is LESS THAN AND EQUAL to 3
#~ is a NOT operator
np_array[~(np_array>3)]

array([1, 2, 3])

In [40]:
#EXAMPLE 2 - combining masks with &
np_array[(np_array > 3) & (np_array < 8)] 

array([4, 5, 6, 7])

In [41]:
#EXAMPLE 3 - OR with |
np_array[(np_array < 3) | (np_array > 8)] 

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [43]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [45]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

In [46]:
np_array_2d

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

In [44]:
#EXAMPLE 1 - What is at index 3?
py_list_2d[3]

[4, 'D']

In [48]:
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

In [51]:
#EXAMPLE 2 - What is the FIRST element at index 3?
py_list_2d[3][0]

4

In [54]:
np_array_2d[3,0] #use comma

'4'

In [55]:
#EXAMPLE 3 - What are the first 3 elements?
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [56]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [59]:
#EXAMPLE 4 - take 3 elements, then the first element '0' of the 3 it toook
py_list_2d[:3][0]

[1, 'A']

In [60]:
np_array_2d[:3,0]

array(['1', '2', '3'], dtype='<U21')

In [61]:
py_list_2d[:3][1]

[2, 'B']

In [62]:
#EXAMPLE 5
py_list_2d[3:6][0] #the first element of the list that starts from the index 3

[4, 'D']

In [64]:
np_array_2d[3:6,0] #the first element in the list of all from the sliced list

array(['4', '5', '6'], dtype='<U21')

In [66]:
np_array_2d[:,0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

In [68]:
#EXAMPLE 1 - creating larger list from a smaller one
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [69]:
#EXAMPLE 2 - 3 WAYS TO GROW THE LIST

In [70]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [71]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [73]:
#very fast
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [80]:
#EXAMPLE 3 - incorporating multiple elements using extend() and append ()
#adding elements to a list
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [78]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [81]:
x=[1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

with (), Cannot be changed after creation

In [92]:
[1,2,3] #this is a list

[1, 2, 3]

In [93]:
(1,2,3) #this is a tuple, and this cannot be modified

(1, 2, 3)

In [94]:
a=(1, 2, 3)     # Define the above tuple

In [85]:
print(a[0]) 

1


In [87]:
# The following will NOT work because the tuple cant be changed
a[0]=-1
a[0]+= [10]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [90]:
#ONLY USE .copy() to copy lists to another variable, dont y=x it

In [104]:
x=[1, 2, 3]
y=x
z=x

In [113]:
print(f'{id(x)=}, {id(y)=}, {id(z)=}') #all ids the same

id(x)=4423202368, id(y)=4423190720, id(z)=4423200192


In [114]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()
print(f'{id(x)=}, {id(y)=}, {id(z)=}')

id(x)=4422232192, id(y)=4423190208, id(z)=4423222848


## Footnotes