<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [6]:
import numpy as np

# What to expect in this chapter

Storing and managing data:
1. Lists
2. Numpy arrays
3. Dictionaries
4. Tuples

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [3]:
#PYTHON LISTS - Order is important
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [7]:
#NUMPY ARRAYS - Order is important
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [10]:
#DICTIONARY - Key and associated value seaparted by ':', hence do not need 2 lists
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

Python is a zero-index language and indexing starts at 0.

[a,b,c,d]: a is index 0, b is 1, c is 2, d is 3

In [13]:
#Example 1
py_real_names[0]

'Natasha Romanoff'

In [15]:
#Example 2
py_super_names[0]

'Black Widow'

In [18]:
#Example 3 - INTRODUCING REVERSE IDNEXING
py_super_names[2]    # Forward indexing requires knowledge of the size of the list

'Doctor Strange'

In [20]:
py_super_names[-1] #Reverse indexing

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [28]:
#Dcitionaries have a 'key:value' structure, such that in 'a:b': a is key, b is value
superhero_info["Natasha Romanoff"]         

'Black Widow'

In [26]:
#To access all the keys
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [27]:
#To access all the values
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [35]:
#Have a 2D list/array to avoid having 2 lists to store things (this is also called a nested list)
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                   ['Stephen Strange', 'Doctor Strange']]

In [37]:
py_superhero_info[1] #This returns the second 'item' of both the lists

['Tony Stark', 'Iron Man']

# 2 Lists vs. Arrays

Differences between lists and arrays

In [46]:
#Convert python list to np array list like this:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list above to create a numpy array

## 2.1 Size

Use len() functions to know the number of items in lists OR arrays

In [47]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]
np_array_2d = np.array(py_list_2d)      # Reusing the Python list above to create a numpy array

In [42]:
#len() function on the PYTHON LIST above
len(py_list_2d)

10

In [49]:
#len() function on the numpy array above
len(np_array_2d)

10

Use .shape attribute/property of the numpy array to find 
1. the number of items in each 'dimension'

In [60]:
np_array_2d.shape #Testing .shape function on nested array
#This array has 2 dimensions, the first dimension has 10  elements, the second has 2: hence, returning (10,2)

(10, 2)

## 2.2 Arrays are fussy about type

Arrays should only have one single data type, lists can have multiple.

In [62]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [63]:
#LIST
py_list

[1, 1.5, 'A']

In [64]:
#ARRAY
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [65]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)       

In [67]:
#LISTS
py_list + 10 #Doesnt work

TypeError: can only concatenate list (not "int") to list

In [69]:
np_array + 10 #Adds the int value 10 to each element in the array

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [70]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [73]:
#LIST - Combines the 2 lists into one large list (non-nested)
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [75]:
#ARRAY - Adds element of one list to the element of the same index in the other list
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

In [77]:
#ARRAY (trying to add 2 arrays with different sizes FOR FUN) - REALISED IT DOESNT WORK
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50,60]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)
np_array_1 + np_array_2

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

## 2.5 Multiplying by a Number 

Use '*'

In [78]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [84]:
#LISTS - Just repeats the same list n number of times, grows the list
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [83]:
#ARRAYS - Multiplies each element by 2
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

Use '**'

In [85]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [87]:
#LISTS - DOESNT WORK
py_list**2                    

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [89]:
#ARRAYS - Squares the elements in the array
np_array**2

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

Asking questions with '==' (Works mainly in arrays only)

In [90]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [95]:
#LISTS - Example 1
py_list == 3     # Works- the question is 'Is the list 3?'

False

In [96]:
#LISTS - Example 2
py_list > 3      # Won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

In [99]:
#ARRAYS - Example 1 Tests for each element
np_array == 3  

array([False, False,  True, False, False])

In [100]:
#ARRAYS - Example 2 Tests for each element
np_array > 3  

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [101]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [106]:
#LISTS - Example 1: sum() adds all the elements together
sum(py_list)    

15

In [108]:
#LISTS - Example 2: max() returns the element of the highest value in the list
max(py_list)    

5

In [109]:
#LISTS - Example 3: min() returns the element of the lowest value in the list
min(py_list) 

1

In [112]:
#LISTS - Example 4: USING ARRAY SYNTAX, as sum is not an attribute
py_list.sum()

AttributeError: 'list' object has no attribute 'sum'

In [121]:
#ARRAYS - Example 1: .sum() adds all the elements in the array
np_array.sum()

15

In [122]:
#ARRAYS - Example 2: .max() returns element of highest value in the array
np_array.max()

5

In [123]:
#ARRAYS - Example 3: .min() returns element of lowest value in the array
np_array.min()

1

In [124]:
#ARRAYS - Example 4: .mean() returns mean of all the elements in the array
np_array.mean()

3.0

In [125]:
#ARRAYS - Example 4: .std() returns standard deviation of all the elements in the array
np_array.std()

1.4142135623730951

# Exercises & Self-Assessment

#EXERCISE 1

1. 2 SIMILIARITIES BETWEEN LISTS AND ARRAYS
- Lists and arrays store elements in a sequential manner that are based on zero-index language.
- *Order of elements is important, need multiple lists/nested lists to store different sets of elements*

2. 2 DIFFERENCES BETWEEN LISTS AND ARRAYS
- Arrays can only hold elements of the same data type. Lists can usually contain elements of different data types.
- Squaring and adding interer values do not work in python lists but do in arrays

3. What is a dictionary?
- A dictionary is a data structure that stores data as key-value pairs. Each key in the dictionary has a specific value, forming a mapping between keys and their corresponding values. 

## Footnotes